
package com.exam4server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "clientservice", targetNamespace = "http://www.exam4server.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Clientservice {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.RegisterResponse")
    @Action(input = "http://www.exam4server.com/clientservice/registerRequest", output = "http://www.exam4server.com/clientservice/registerResponse")
    public boolean register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "querylist", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Querylist")
    @ResponseWrapper(localName = "querylistResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.QuerylistResponse")
    @Action(input = "http://www.exam4server.com/clientservice/querylistRequest", output = "http://www.exam4server.com/clientservice/querylistResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://www.exam4server.com/clientservice/querylist/Fault/ParseException")
    })
    public String querylist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletelist", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Deletelist")
    @ResponseWrapper(localName = "deletelistResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.DeletelistResponse")
    @Action(input = "http://www.exam4server.com/clientservice/deletelistRequest", output = "http://www.exam4server.com/clientservice/deletelistResponse")
    public boolean deletelist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearlist", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Clearlist")
    @ResponseWrapper(localName = "clearlistResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.ClearlistResponse")
    @Action(input = "http://www.exam4server.com/clientservice/clearlistRequest", output = "http://www.exam4server.com/clientservice/clearlistResponse")
    public boolean clearlist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addlist", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Addlist")
    @ResponseWrapper(localName = "addlistResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.AddlistResponse")
    @Action(input = "http://www.exam4server.com/clientservice/addlistRequest", output = "http://www.exam4server.com/clientservice/addlistResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://www.exam4server.com/clientservice/addlist/Fault/ParseException")
    })
    public boolean addlist(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws ParseException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isright", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.Isright")
    @ResponseWrapper(localName = "isrightResponse", targetNamespace = "http://www.exam4server.com", className = "com.exam4server.IsrightResponse")
    @Action(input = "http://www.exam4server.com/clientservice/isrightRequest", output = "http://www.exam4server.com/clientservice/isrightResponse")
    public boolean isright(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
