
package com.exam4server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientServiceService", targetNamespace = "http://www.exam4server.com", wsdlLocation = "http://127.0.0.1:8002/webservice/clientservice?wsdl")
public class ClientServiceService
    extends Service
{

    private final static URL CLIENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSERVICESERVICE_EXCEPTION;
    private final static QName CLIENTSERVICESERVICE_QNAME = new QName("http://www.exam4server.com", "ClientServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8002/webservice/clientservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSERVICESERVICE_WSDL_LOCATION = url;
        CLIENTSERVICESERVICE_EXCEPTION = e;
    }

    public ClientServiceService() {
        super(__getWsdlLocation(), CLIENTSERVICESERVICE_QNAME);
    }

    public ClientServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSERVICESERVICE_QNAME, features);
    }

    public ClientServiceService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSERVICESERVICE_QNAME);
    }

    public ClientServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSERVICESERVICE_QNAME, features);
    }

    public ClientServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Clientservice
     */
    @WebEndpoint(name = "clientserviceport")
    public Clientservice getClientserviceport() {
        return super.getPort(new QName("http://www.exam4server.com", "clientserviceport"), Clientservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Clientservice
     */
    @WebEndpoint(name = "clientserviceport")
    public Clientservice getClientserviceport(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.exam4server.com", "clientserviceport"), Clientservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSERVICESERVICE_EXCEPTION!= null) {
            throw CLIENTSERVICESERVICE_EXCEPTION;
        }
        return CLIENTSERVICESERVICE_WSDL_LOCATION;
    }

}
